server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: member
          uri: http://localhost:8090
          predicates:
            - Path=/api/client/**
        - id: account
          uri: http://localhost:9090
          predicates:
            - Path=/api/account/**
        - id: movements
          uri: http://localhost:9090
          predicates:
            - Path=/api/movements/**